### ISSUE TITLE
Error with Bard Fields Post-Update: 'textAlign Button/Extension Not Enabled

### ISSUE THREAD

**Issue by Oleafeon** [OptimoApps/statamic-bard-text-align#23]
We ran into a problem because of an update. I don't know if this is a problem that can be solved, but after we upgraded our Statamic to Statamic4, we had to remove your plugin because it's added as a core feature now. However, now all the Bard fields that were using your plugin are showing the following error: 'Invalid content, textAlign button/extension is not enabled.' We have a lot of entries, so it's not easily changed in the files. Do you have an idea on how we can rewrite this quickly?

**Comment by ssatz** [comment]
Yes it has been added into the core. If you remove the plugin it should work. Quick guess might be a cache issue.  Do post me the error screenshot if you have?

**Comment by Oleafeon** [comment]
I tried a cache clear no luck, this does not result in a log file but i have the error i get here:
![image](https://github.com/OptimoApps/statamic-bard-text-align/assets/20043831/575fdb89-3d96-4e23-b640-0670a461ffde)

**Comment by ssatz** [comment]
@mkwia Upon the removal of the extension, the marks are manually added and cannot be erased thereafter. @jasonvarga do you have any suggestions for this issue.

**Comment by Oleafeon** [comment]
Any updates on this issue

**Comment by jasonvarga** [comment]
Text align was added to core in 3.4, not 4.0. See https://github.com/statamic/cms/pull/6450

If you want to remove this extension and use the native one, you'll need to update the prosemirror in your content files. Not really a way around that.

However, this addon was updated to work for 3.4. See: https://github.com/OptimoApps/statamic-bard-text-align/pull/19 You could just keep this installed and use it instead of the native text align feature by disabling the buttons on the Bard fields.

I see that the `composer.json` of this package doesn't support Statamic 4.0. It can probably be supported just by bumping the Composer requirement. // @ssatz

**Comment by ssatz** [comment]
Tagged V1.0.4 is now available, compatible with Statamic 4.0. We believe this release addresses the reported issue. Please note that as this addon has been integrated into the Statamic core, there will be no further updates from our end.
